<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>
        // 为了更好的往下扩展Promise的应用，这里需要先跟大家介绍一下Promsie的基础知识。

        /* 
        一、 Promise对象有三种状态，他们分别是：
            pending: 等待中，或者进行中，表示还没有得到结果
            resolved(Fulfilled): 已经完成，表示得到了我们想要的结果，可以继续往下执行
            rejected: 也表示得到结果，但是由于结果并非我们所愿，因此拒绝执行

        这三种状态不受外界影响，而且状态只能从pending改变为resolved或者rejected，并且不可逆。
        在Promise对象的构造函数中，将一个函数作为第一个参数。
        而这个函数，就是用来处理Promise的状态变化。

        new Promise(function(resolve, reject) {
            if(true) { resolve() };
            if(false) { reject() };
        })
        上面的resolve和reject都为一个函数，他们的作用分别是将状态修改为resolved和rejected。

        */

        // 二、 Promise对象中的then方法，可以接收构造函数中处理的状态变化，并分别对应执行。
        // then方法有2个参数，第一个函数接收resolved状态的执行，第二个参数接收reject状态的执行。
        /* function fn(num) {
            return new Promise(function(resolve, reject) {
                if (typeof num == 'number') {
                    resolve();
                } else {
                    reject();
                }
            }).then(function() {
                console.log('参数是一个number值');
            }, function() {
                console.log('参数不是一个number值');
            })
        }

        fn('hahha');
        fn(1234); */


        // then方法的执行结果也会返回一个Promise对象。
        // 因此我们可以进行then的链式执行，这也是解决回调地狱的主要方式。

        function fn(num) {
            var p = new Promise(function (resolve, reject) {
                    if (typeof num == 'number') {
                        resolve(1);
                    } else {
                        reject('失败');
                    }
                })
                .then(function (res) {
                    console.log('参数是一个number值1', res);
                    throw new Error("提示文字")
                    return res + 1
                }, function (err) {
                    console.log('err', err);
                    throw new Error("提示文字")
                })
            return p

            // .then(function() {
            //     console.log('参数是一个number值3');
            // })
            // .then(null, function() {
            //     console.log('参数不是一个number值1');
            // })
            // .then(null, function() {
            //     console.log('参数不是一个number值2');
            // })
            // .then(null, function() {
            //     console.log('参数不是一个number值3');
            // })
            // .then(function() {
            //     console.log('参数是一个number值4');
            // })
            // .then(function() {
            //     console.log('参数是一个number值5');
            // })
            // .then(function() {
            //     console.log('参数是一个number值6');
            // })
            // .then(function() {
            //     console.log('参数是一个number值7');
            // })
            // .then(null, function() {
            //     console.log('参数不是一个number值4');
            // })
            // .then(null, function() {
            //     console.log('参数不是一个number值5');
            // })
            // .then(function() {
            //     console.log('参数是一个number值8');
            // })
            // .then(function() {
            //     console.log('参数是一个number值9');
            // })

        }

        // fn(1234);    // 1,2,3,4,5,6,7,8,9
        var p = fn('haha');
        p.then(function (res) {
            console.log('第2次then，res', res)
        }, function (err) {
            console.log('第2次then，err', err)
        }).then((res) => {
            console.log('第3次then，res', res)
        }, (err) => {
            console.log('第3次then，err', err)

        })
        console.log(p);


        // fn('hahha')  // not1,4,5,6,7,8,9

        // then(null, function() {}) 就等同于catch(function() {})
    </script>
</body>

</html>